import os
import openai

def chat_model(system_content: str, user_content: str, api_key: str):
  """
  Generates a chat-based response using the OpenAI GPT-3.5 Turbo model.

  Args:
    system_content (str): The content of the system message.
    user_content (str): The content of the user message.
    api_key (str): The API key for accessing the OpenAI API.

  Returns:
    completion: The response generated by the chat model.

  Raises:
    None

  Example:
    system_content = "Hello, how can I assist you today?"
    user_content = "What is the weather like tomorrow?"
    api_key = "your-api-key"

    response = chat_model(system_content, user_content, api_key)
    print(response)
  """
  openai.api_key = api_key

  completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
      {"role": "system", "content": system_content},
      {"role": "user", "content": user_content}
    ]
  )

  return completion